"""Initial schema creation

Revision ID: 2e28016d76c0
Revises: 
Create Date: 2026-06-28 13:29:30.705240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e28016d76c0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=True),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index('idx_action_audit', 'audit_logs', ['action'], unique=False)
    op.create_index('idx_user_audit', 'audit_logs', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('telegram_id', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('collections',
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.user_id'], ),
    sa.PrimaryKeyConstraint('collection_id')
    )
    op.create_index('idx_user_collection', 'collections', ['user_id'], unique=False)
    op.create_table('conversations',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.user_id'], ),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_index('idx_user_conversation', 'conversations', ['user_id'], unique=False)
    op.create_table('cost_tracking',
    sa.Column('cost_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('requests_count', sa.Integer(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.user_id'], ),
    sa.PrimaryKeyConstraint('cost_id')
    )
    op.create_index('idx_user_date_cost', 'cost_tracking', ['user_id', 'date'], unique=False)
    op.create_table('entities',
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.user_id'], ),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_index('idx_user_entity', 'entities', ['user_id'], unique=False)
    op.create_table('entity_relations',
    sa.Column('relation_id', sa.UUID(), nullable=False),
    sa.Column('entity_a_id', sa.UUID(), nullable=False),
    sa.Column('entity_b_id', sa.UUID(), nullable=False),
    sa.Column('relation_type', sa.String(length=100), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entity_a_id'], ['entities.entity_id'], ),
    sa.ForeignKeyConstraint(['entity_b_id'], ['entities.entity_id'], ),
    sa.PrimaryKeyConstraint('relation_id')
    )
    op.create_index('idx_entity_relation', 'entity_relations', ['entity_a_id', 'entity_b_id'], unique=False)
    op.create_table('messages',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_masked', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.conversation_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index('idx_conversation_message', 'messages', ['conversation_id'], unique=False)
    op.create_table('sources',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.collection_id'], ),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.create_index('idx_collection_source', 'sources', ['collection_id'], unique=False)
    op.create_table('memory_chunks',
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('embedding', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_accessed', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.source_id'], ),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    op.create_index('idx_embedding_chunk', 'memory_chunks', ['embedding'], unique=False, postgresql_using='gin')
    op.create_index('idx_source_chunk', 'memory_chunks', ['source_id'], unique=False)
    op.create_table('chunk_entities',
    sa.Column('chunk_entity_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('mention_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['memory_chunks.chunk_id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.entity_id'], ),
    sa.PrimaryKeyConstraint('chunk_entity_id')
    )
    op.create_index('idx_chunk_entity', 'chunk_entities', ['chunk_id', 'entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_chunk_entity', table_name='chunk_entities')
    op.drop_table('chunk_entities')
    op.drop_index('idx_source_chunk', table_name='memory_chunks')
    op.drop_index('idx_embedding_chunk', table_name='memory_chunks', postgresql_using='gin')
    op.drop_table('memory_chunks')
    op.drop_index('idx_collection_source', table_name='sources')
    op.drop_table('sources')
    op.drop_index('idx_conversation_message', table_name='messages')
    op.drop_table('messages')
    op.drop_index('idx_entity_relation', table_name='entity_relations')
    op.drop_table('entity_relations')
    op.drop_index('idx_user_entity', table_name='entities')
    op.drop_table('entities')
    op.drop_index('idx_user_date_cost', table_name='cost_tracking')
    op.drop_table('cost_tracking')
    op.drop_index('idx_user_conversation', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('idx_user_collection', table_name='collections')
    op.drop_table('collections')
    op.drop_table('user_profiles')
    op.drop_index('idx_user_audit', table_name='audit_logs')
    op.drop_index('idx_action_audit', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
