"""Add Telegram idempotency tracking

Revision ID: 480a02d8128c
Revises: 2e28016d76c0
Create Date: 2026-06-28 13:41:17.324080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '480a02d8128c'
down_revision: Union[str, Sequence[str], None] = '2e28016d76c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_update_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('update_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_update_id_expires', 'telegram_update_log', ['update_id', 'expires_at'], unique=False)
    op.create_index(op.f('ix_telegram_update_log_update_id'), 'telegram_update_log', ['update_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telegram_update_log_update_id'), table_name='telegram_update_log')
    op.drop_index('idx_update_id_expires', table_name='telegram_update_log')
    op.drop_table('telegram_update_log')
    # ### end Alembic commands ###
