"""Add PII redaction logging table

Revision ID: a98554c378c2
Revises: c171809b7ee2
Create Date: 2026-06-28 15:14:31.432660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a98554c378c2'
down_revision: Union[str, Sequence[str], None] = 'c171809b7ee2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pii_redaction_logs',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('pii_types', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('pii_count', sa.Integer(), nullable=False),
    sa.Column('sample_entities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index('idx_message_pii', 'pii_redaction_logs', ['message_id'], unique=False)
    op.create_index('idx_user_pii_redaction', 'pii_redaction_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_pii_redaction', table_name='pii_redaction_logs')
    op.drop_index('idx_message_pii', table_name='pii_redaction_logs')
    op.drop_table('pii_redaction_logs')
    # ### end Alembic commands ###
