"""Add password_hash to user_profiles

Revision ID: c171809b7ee2
Revises: 480a02d8128c
Create Date: 2026-06-28 15:05:59.669280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c171809b7ee2'
down_revision: Union[str, Sequence[str], None] = '480a02d8128c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('password_hash', sa.String(length=255), nullable=False))
    op.alter_column('user_profiles', 'telegram_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user_profiles', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_unique_constraint(None, 'user_profiles', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_profiles', type_='unique')
    op.alter_column('user_profiles', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user_profiles', 'telegram_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('user_profiles', 'password_hash')
    # ### end Alembic commands ###
